(()=>{
 if(document.querySelector('tech-hub-navigation')||/^\/full\/?$/.test(location.pathname))return;
 const host=document.createElement('tech-hub-navigation'),shadow=host.attachShadow({mode:'open'});
 const style=document.createElement('link');style.rel='stylesheet';style.href='/__hub/chrome.css';
 shadow.append(style);const bar=document.createElement('div');bar.className='bar';const brand=document.createElement('span');brand.className='brand';brand.textContent='TH';const picker=document.createElement('label');picker.className='picker';const select=document.createElement('select');select.setAttribute('aria-label','Switch application');picker.append(select);const settings=document.createElement('button');settings.textContent='Settings';settings.hidden=true;bar.append(brand,picker,settings);shadow.append(bar);
 let state,signature='',dirty=false,revision=null;
 window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
 function discard(){return !dirty||confirm('Discard unsaved settings?');}
 async function refresh(){try{const r=await fetch('/__hub/navigation');if(!r.ok)return;state=await r.json();if(document.body.dataset.techhubRecovery&&!state.authRequired&&state.services.some(s=>s.id===state.current&&s.state==='running')){location.reload();return;}document.documentElement.dataset.techHubService=state.current;host.style.setProperty('--service-accent',state.current==='ultrix'?'#55b5ff':state.current==='record'?'#ff727c':'#ff8a1f');if(!host.isConnected)document.body.prepend(host);settings.hidden=!state.settings||(state.current==='ultrix'&&location.pathname.startsWith('/setup'));bar.querySelector('.recovery')?.remove();if(state.message){const notice=make('p',state.message);notice.className='notice recovery';if(state.authRequired){const signIn=make('a',' Sign in again');signIn.href='/__hub/login';signIn.style.color='var(--service-accent,#ff8a1f)';notice.append(signIn);}bar.append(notice);}const next=JSON.stringify(state);if(next===signature)return;signature=next;select.replaceChildren();const choices=state.services.map(s=>({...s,label:s.name+(s.protected?' · Password protected':'')+(s.state==='running'?'':' · '+s.state)}));if(state.local)choices.unshift({id:'master',label:'Tech Hub · Master page',port:state.adminPort});if(!choices.some(s=>s.id===state.current))choices.unshift({id:state.current,label:'Service is off',disabled:true});for(const s of choices){const o=document.createElement('option');o.textContent=s.label;o.value=s.id;o.disabled=!!s.disabled;o.selected=s.id===state.current;select.append(o);}}catch{/* Keep a loaded service usable while the hub reconnects. */}}
 select.onchange=()=>{const s=state.services.find(s=>s.id===select.value);const url=new URL(location.href);url.port=String(s?s.port:state.adminPort);url.pathname='/';url.search='';url.hash='';location.assign(url.href);};
 const modal=document.createElement('dialog');shadow.append(modal);
 const make=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
 async function loadSettings(){settings.disabled=true;try{const r=await fetch('/__hub/settings');const config=await r.json();if(!r.ok)throw Error(config.error);revision=r.headers.get('etag');renderSettings(config);}catch(error){const message=make('p',error.message);message.className='notice error';bar.querySelector('.notice')?.remove();bar.append(message);}finally{settings.disabled=false;}}
 // Router Panel has its own settings page (several routers, categories, profiles); Record Monitor uses the modal.
 settings.onclick=()=>{if(state.current==='ultrix'){if(discard())location.assign('/setup');return;}loadSettings();};
 function renderSettings(config){
 dirty=false;modal.replaceChildren();const form=make('form'),title=make('h2','Record Monitor settings'),help=make('p','Settings apply live. Only added, removed or changed recorder connections are affected.');form.append(title,help);const fields=make('div');fields.className='fields';form.append(fields);const bindings=[];
 function field(parent,label,value,type='text',apply){const wrap=make('label',label),input=make('input');input.type=type;if(type==='checkbox'){wrap.className='check';input.checked=!!value;}else input.value=value??'';wrap.append(input);parent.append(wrap);if(apply)bindings.push(()=>apply(type==='checkbox'?input.checked:type==='number'?Number(input.value):input.value));return input;}
 let devices=[];
 if(state.current==='record'){
 field(fields,'Poll interval (milliseconds)',config.pollIntervalMs,'number',v=>config.pollIntervalMs=v).min='250';
 field(fields,'Low space warning (%)',config.warnFreePercent??20,'number',v=>config.warnFreePercent=v);
 field(fields,'Critical space warning (%)',config.criticalFreePercent??10,'number',v=>config.criticalFreePercent=v);
 for(const [key,label] of [['controlEnabled','Enable recorder controls'],['controlLocalOnly','Controls only on this computer'],['confirmStop','Confirm before stopping'],['allowFormat','Allow disk formatting']])field(fields,label,config[key],'checkbox',v=>config[key]=v);
 form.append(make('h3','Recorders'));const list=make('div');form.append(list);
 function addDevice(value={type:'hyperdeck',name:'',host:''}){const item=make('section');item.className='device';const group=make('div');group.className='fields';item.append(group);const name=field(group,'Name',value.name),host=field(group,'IP address or hostname',value.host);host.required=true;const wrap=make('label','Recorder type'),type=make('select');for(const [id,label] of [['hyperdeck','Blackmagic HyperDeck'],['kipro','AJA Ki Pro']]){const o=make('option',label);o.value=id;type.append(o);}type.value=value.type;wrap.append(type);group.append(wrap);const port=field(group,'Port (optional)',value.port,'number');port.min='1';port.max='65535';const remove=make('button','Remove recorder');remove.type='button';remove.onclick=()=>{devices=devices.filter(d=>d.item!==item);item.remove();};item.append(remove);list.append(item);devices.push({item,read:()=>{const d={...value,name:name.value.trim(),host:host.value.trim(),type:type.value};if(port.value)d.port=Number(port.value);else delete d.port;return d;}});}
 for(const d of config.devices)addDevice(d);const add=make('button','Add recorder');add.type='button';add.onclick=()=>addDevice();form.append(add);
 }
 const error=make('p');error.className='error';error.setAttribute('role','alert');form.append(error);const actions=make('div');actions.className='actions';const cancel=make('button','Cancel');cancel.type='button';cancel.onclick=()=>{if(discard()){dirty=false;modal.close();}};const save=make('button','Save settings');save.className='primary';save.type='submit';actions.append(cancel,save);form.append(actions);modal.append(form);form.addEventListener('input',()=>dirty=true);form.addEventListener('change',()=>dirty=true);form.addEventListener('click',e=>{if(e.target.closest('button')&&!['Cancel','Save settings'].includes(e.target.textContent))dirty=true;});modal.oncancel=e=>{if(!discard())e.preventDefault();else dirty=false;};modal.showModal();
 form.onsubmit=async e=>{e.preventDefault();save.disabled=true;error.textContent='';try{for(const bind of bindings)bind();if(state.current==='record')config.devices=devices.map(d=>d.read());const r=await fetch('/__hub/settings',{method:'POST',headers:{'Content-Type':'application/json',...(revision?{'If-Match':revision}:{})},body:JSON.stringify(config)});const result=await r.json();if(!r.ok)throw Error(result.error);dirty=false;modal.close();const message=make('p','Settings saved and applied.');message.className='notice';bar.append(message);}catch(e){error.textContent=e.message;}finally{save.disabled=false;}};
 }
 refresh();setInterval(refresh,5000);
})();
